name: Deploy FastAPI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: false
        default: latest

permissions:
  packages: read

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/fastapi-app

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
          -u "${{ github.actor }}" \
          --password-stdin


      - name: Pull image
        run: |
          docker pull $IMAGE_NAME:${{ github.event.inputs.tag }}


      - name: Deploy containers
        run: |
          export IMAGE_NAME=$IMAGE_NAME
          export IMAGE_TAG=${{ github.event.inputs.tag }}

          docker compose down || true
          docker compose up -d


      - name: Cleanup old images
        run: |
          docker image prune -af


      - name: Check running containers
        run: |
          docker ps
