name: Deploy FastAPI App

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string


jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Debug
        run: |
          echo "Deploying version ${{ inputs.version }}"


      - name: Checkout release version
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}


      - name: Deploy
        run: |
          docker compose down
          docker compose up --build -d


      - name: Check containers
        run: |
          docker ps
