name: Deploy FastAPI App

on:
  release:
    types:
      - published

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Debug
        run: |
          echo "Release triggered"
          echo "Version: ${{ github.event.release.tag_name }}"

      - name: Checkout released version
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Deploy
        run: |
          docker compose up --build -d
