# # name: Deploy FastAPI App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           clean: false

#       - name: Print workspace info
#         run: |
#           echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
#           pwd
#           ls -la

#       - name: Docker Compose Build and Start
#         run: |
#           cd $GITHUB_WORKSPACE
#           docker compose up --build -d

#       - name: Show running containers
#         run: docker ps
